"""Tests core.parsing's PDF path: camelot (flavor="stream") extraction
via parse_file_raw(), and the page-gluing decision in
_glue_pdf_page_grids(). Mirrors the rigor of tests/test_parsing.py's
Excel/CSV tests — real fixture files on disk, values checked by equality
(not by eyeballing console output, which mangles Cyrillic on Windows —
see README), not just "it didn't crash".

Fixtures live in backend/tests/fixtures/ (generated by
backend/tests/fixtures/generate_fixtures.py) alongside the existing
Excel/CSV fixture library, per project convention.
"""

from decimal import Decimal
from pathlib import Path

import pytest

from core.parsing import UnsupportedFileError, _glue_pdf_page_grids, parse_file_raw

FIXTURES_DIR = Path(__file__).parent.parent / "backend" / "tests" / "fixtures"


def test_pdf_no_borders_extracted_via_stream_flavor():
    """The core claim from README's benchmark: a table with no drawn cell
    borders (text-position aligned only) comes back correctly using
    flavor="stream" — the whole reason that flavor, not the default, was
    chosen."""
    result = parse_file_raw(FIXTURES_DIR / "pdf_invoice_no_borders.pdf")
    assert result.detected_encoding is None
    assert result.detected_delimiter is None
    assert result.df.height == 2  # header row + 1 data row, nothing assumed
    rows = result.df.rows()
    assert rows[0] == ("Товар", "Кол-во", "Сумма")
    assert rows[1] == ("хлеб бородинский", "25", "1875")


def test_pdf_multipage_table_glues_pages_and_drops_repeated_headers():
    """3-page table, identical header row on every page. Must come back
    as ONE grid: page 1's header kept once, the duplicate header dropped
    from pages 2 and 3 — not 3 separate header rows, not 3 separate
    tables."""
    result = parse_file_raw(FIXTURES_DIR / "pdf_multipage_table.pdf")
    rows = result.df.rows()

    assert rows[0] == ("Товар", "Кол-во", "Сумма")
    header_occurrences = sum(1 for r in rows if r == ("Товар", "Кол-во", "Сумма"))
    assert header_occurrences == 1, "the repeated per-page header must be deduplicated"

    assert result.df.height == 13  # 1 header + 4 + 4 + 4 data rows across 3 pages

    # Independently-known total (see generate_fixtures.py's own Decimal sum
    # printed at generation time) — proves no row was dropped or duplicated
    # by the glue, not just that the row count matches.
    total = sum((Decimal(r[2]) for r in rows[1:]), Decimal("0"))
    assert total == Decimal("79390.55")


def test_pdf_unsupported_when_no_table_found():
    """A genuinely blank PDF page — no text at all — is the one case
    camelot itself reports zero Table objects for (verified live: a page
    with SOME text but no tabular structure still comes back as a
    degenerate 1x1 "table" containing that text, so it's not usable to
    trigger this path — an empty page is). Must raise the same
    UnsupportedFileError as any other file parse_file_raw() can't make
    sense of, not crash with an internal IndexError from empty-list
    handling. Uses the committed pdf_blank_page.pdf fixture rather than
    generating one inline, so this test doesn't need reportlab installed
    wherever pytest runs (e.g. the production server deliberately doesn't
    have it — see generate_fixtures.py)."""
    with pytest.raises(UnsupportedFileError):
        parse_file_raw(FIXTURES_DIR / "pdf_blank_page.pdf")


@pytest.mark.parametrize(
    "label,content",
    [
        # Most malformed content -> playa.exceptions.PDFException.
        ("syntax_error", b"%PDF-1.4 not really a valid pdf body"),
        ("truncated_after_header", b"%PDF-1.4\n%%EOF"),
        ("no_root_object", b"%PDF-1.4\n1 0 obj\n<<>>\nendobj\n"),
        ("binary_garbage", b"\x00\x01\x02\x03\x04garbage binary"),
        ("not_a_pdf_at_all", b"not a pdf at all, random garbage bytes 12345"),
        # This specific shape escapes as a bare StopIteration from
        # playa's trailer reader (document.py's `next(...)` has no
        # except of its own) instead of a PDFException subclass —
        # verified live against the deployed server: an earlier version
        # of _read_pdf_raw() only caught PDFException, so this exact
        # byte string produced an unhandled 500 ("RuntimeError: coroutine
        # raised StopIteration", from PEP 479's handling of a
        # StopIteration that crosses an `async def` boundary).
        ("stop_iteration_leak", b"%PDF-1.4 not a real pdf\n"),
    ],
)
def test_pdf_malformed_bytes_raise_unsupported_not_a_raw_pdf_exception(tmp_path, label, content):
    """A file with a .pdf extension whose content isn't actually a valid
    PDF (corrupt upload, wrong file renamed, etc.) must raise the same
    UnsupportedFileError every other bad input raises — never leak one of
    camelot/playa's internal, undocumented exception types up through the
    API as an unhandled 500. Each variant here is a real byte string that
    was empirically found (not assumed) to trigger a DIFFERENT underlying
    exception type deep inside camelot's PDF backend."""
    path = tmp_path / f"corrupt_{label}.pdf"
    path.write_bytes(content)

    with pytest.raises(UnsupportedFileError):
        parse_file_raw(path)


def test_pdf_empty_file_raises_unsupported_not_a_bare_valueerror(tmp_path):
    """A genuinely empty .pdf (0 bytes) hits Python's own mmap module
    before playa even starts parsing — mmap.mmap() on an empty file
    raises a bare ValueError("cannot mmap an empty file"), a third
    distinct exception shape (see the parametrized test above for the
    other two) that must still come back as UnsupportedFileError."""
    path = tmp_path / "empty.pdf"
    path.write_bytes(b"")

    with pytest.raises(UnsupportedFileError):
        parse_file_raw(path)


def test_pdf_malformed_upload_does_not_leak_an_open_file_handle(tmp_path):
    """Regression guard for the Windows PermissionError bug this module's
    exception handling exists to avoid: after parse_file_raw() raises
    UnsupportedFileError for a corrupt PDF, the caller must be able to
    delete the file immediately (mirrors backend/main.py's /api/upload,
    which writes the upload to a temp file and os.unlink()s it in a
    `finally` block right after calling parse_file_raw())."""
    path = tmp_path / "corrupt.pdf"
    path.write_bytes(b"%PDF-1.4 not a real pdf\n")  # the StopIteration-leak shape

    with pytest.raises(UnsupportedFileError):
        parse_file_raw(path)

    path.unlink()  # must not raise PermissionError


# --- _glue_pdf_page_grids() unit tests: exercise the decision logic
# directly with synthetic grids, since reliably forcing camelot itself to
# disagree about column count across pages (the fallback branch) isn't
# practical to construct as a real PDF fixture. ---


def test_glue_single_page_returned_unchanged():
    grid = [["Товар", "Сумма"], ["Носки", "100"]]
    assert _glue_pdf_page_grids([grid]) == grid


def test_glue_matching_headers_dedups_repeats():
    page1 = [["Товар", "Сумма"], ["Носки", "100"], ["Шапка", "200"]]
    page2 = [["Товар", "Сумма"], ["Ботинки", "300"]]
    glued = _glue_pdf_page_grids([page1, page2])
    assert glued == [
        ["Товар", "Сумма"],
        ["Носки", "100"],
        ["Шапка", "200"],
        ["Ботинки", "300"],
    ]


def test_glue_mismatched_headers_falls_back_to_honest_concatenation():
    """Headers differ across pages — must NOT guess which one is "the"
    header. Every row from every page comes through, in page order,
    nothing dropped."""
    page1 = [["Товар", "Сумма"], ["Носки", "100"]]
    page2 = [["Наименование", "Итого"], ["Шапка", "200"]]  # different header text
    glued = _glue_pdf_page_grids([page1, page2])
    assert glued == [
        ["Товар", "Сумма"],
        ["Носки", "100"],
        ["Наименование", "Итого"],
        ["Шапка", "200"],
    ]


def test_glue_mismatched_column_counts_pads_instead_of_dropping_data():
    """camelot found a different number of columns on different pages — a
    sign its own per-page detection diverged. Must not silently drop the
    extra column's data; pad the shorter rows instead so nothing is
    lost."""
    page1 = [["Товар", "Кол-во", "Сумма"], ["Носки", "5", "100"]]
    page2 = [["Товар", "Сумма"], ["Шапка", "200"]]  # only 2 columns on this page
    glued = _glue_pdf_page_grids([page1, page2])
    assert glued == [
        ["Товар", "Кол-во", "Сумма"],
        ["Носки", "5", "100"],
        ["Товар", "Сумма", ""],
        ["Шапка", "200", ""],
    ]
